server:
  address: 0.0.0.0
  port: 8080

spring:
  # konfigurasi untuk koneksi db
  datasource:
    driver-class-name: com.mysql.jdbc.Driver

    # sesuaikan name database anda dengan di bawah ini
    url: jdbc:mysql://db:3306/apap_db?useSSL=false&serverTimezone=Asia/Jakarta

    # sesuaikan dengan NAME dan PASSWORD anda dengan username password di bawah ini
    username: apap_user
    password: password1234!

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true

    # pembuatan database (create || create-drop || validate || update)
    hibernate.ddl-auto: create-drop

    show-sql: true
